[project]
name = "abot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aiohttp>=3.13.2",
    "akshare==1.16.99",
    "numpy>=2.2.6",
    "pandas>=2.3.3",
]
